### ISSUE TITLE
Invalid token all the time(tried version 4.3 and 4.4)

### ISSUE THREAD

**Issue by casszhao** [hatebase/Hatebase-API-Docs#1]
Hi, I want to download the hatebase terms by using ＂Get Vocabulary". I have successfully obtained tokens via the postman but every time I use the token with getting vocabulary, it returns  "2546": "Invalid token". 

the queries I have tried:
https://api.hatebase.org/4-4/get_vocabulary?token=YWNCDwcBJgqtoQaYQeYPVvCNAehHbqUG&format=json&language=ENG

Thanks.

**Comment by hatebase** [comment]
Please direct support inquiries to support@hatebase.org.

Also, now that you've publicly posted your API key to GitHub, you should IMMEDIATELY change it.
