### ISSUE TITLE
"Unable to execute retrieveVocabulary" for get_vocabulary with nationality parameter

### ISSUE THREAD

**Issue by joon-e** [hatebase/Hatebase-API-Docs#2]
When using the `nationality` parameter (e.g., `nationality = "CA" as in the example`) in a query to `https://api.hatebase.org/4-4/get_vocabulary`, the response content is `"Unable to execute retrieveVocabulary"`. I am able to retrieve the resultset with all other input parameters (e.g., `ethnicity`, `religion`).

**Comment by timothyquinn** [comment]
Joon-e, can you please try again? If it continues to be a problem, contact us at support@hatebase.org

**Comment by joon-e** [comment]
It works now, thank you!
